name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  build:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@ebanux'
      - run: yarn install
      - run: yarn run build
      - run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.RELEASE_TOKEN}}
